# Generated by Django 3.0.5 on 2020-05-16 17:55

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_remove_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
